<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HomepageSetting;

class AdminPanelSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General
            [
                'key' => 'profile_page_title',
                'value' => 'Admin Panel Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'profile_page_subtitle',
                'value' => 'Manage your admin panel content and settings from one place.',
                'type' => 'textarea',
                'section' => 'admin_panel',
                'max_length' => 200,
            ],
            [
                'key' => 'profile_page_banner_image',
                'value' => '',
                'type' => 'image',
                'section' => 'admin_panel',
                'max_length' => null,
            ],
            // Statistics
            [
                'key' => 'profile_page_stat_1_label',
                'value' => 'Users',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 20,
            ],
            [
                'key' => 'profile_page_stat_1_value',
                'value' => '0',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 10,
            ],
            [
                'key' => 'profile_page_stat_2_label',
                'value' => 'Services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 20,
            ],
            [
                'key' => 'profile_page_stat_2_value',
                'value' => '0',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 10,
            ],
            [
                'key' => 'profile_page_stat_3_label',
                'value' => 'Countries',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 20,
            ],
            [
                'key' => 'profile_page_stat_3_value',
                'value' => '0',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 10,
            ],
            // Sidebar
            [
                'key' => 'admin_panel_sidebar_pinned',
                'value' => 'Pinned',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 30,
            ],
            [
                'key' => 'admin_panel_sidebar_general',
                'value' => 'General',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 30,
            ],
            [
                'key' => 'admin_panel_sidebar_dashboard',
                'value' => 'Dashboard',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_my_profile',
                'value' => 'My Profile',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_users',
                'value' => 'Users',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_doctors',
                'value' => 'Doctors',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_practitioners',
                'value' => 'Practitioners',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_mindfulness_practitioners',
                'value' => 'Mindfulness Practitioners',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_yoga_therapists',
                'value' => 'Yoga Therapists',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_clients',
                'value' => 'Clients',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_translators',
                'value' => 'Translators',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_backend_users',
                'value' => 'Backend Users',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_admins',
                'value' => 'Admins',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_finance_manager',
                'value' => 'Finance Manager',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_content_manager',
                'value' => 'Content Manager',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_user_manager',
                'value' => 'User Manager',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_credentials',
                'value' => 'Credentials',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_testimonials',
                'value' => 'Testimonials',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_services',
                'value' => 'Services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_all_services',
                'value' => 'All Services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_service_packages',
                'value' => 'Service Packages',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_service_categories',
                'value' => 'Service Categories',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_finance',
                'value' => 'Finance',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_packages',
                'value' => 'Packages',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_promo_codes',
                'value' => 'Promo Codes',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_other_fees',
                'value' => 'Other Fees',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_reviews',
                'value' => 'Reviews',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_practitioner_reviews',
                'value' => 'Practitioner',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_master_settings',
                'value' => 'Master Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_roles',
                'value' => 'Roles',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_site_settings',
                'value' => 'Site Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_doctor_settings',
                'value' => 'Doctor Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_specializations',
                'value' => 'Specializations',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_ayurveda_expertises',
                'value' => 'Ayurveda Expertises',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_health_conditions',
                'value' => 'Health Conditions',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_external_therapies',
                'value' => 'External Therapies',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_practitioner_settings',
                'value' => 'Practitioner Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_wellness_consultations',
                'value' => 'Wellness Consultations',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 80,
            ],
            [
                'key' => 'admin_panel_sidebar_body_therapies',
                'value' => 'Massage & Body Therapies',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 80,
            ],
            [
                'key' => 'admin_panel_sidebar_other_modalities',
                'value' => 'Other Modalities',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_client_settings',
                'value' => 'Client Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_consultation_preferences',
                'value' => 'Consultation Preferences',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 80,
            ],
            [
                'key' => 'admin_panel_sidebar_mindfulness_settings',
                'value' => 'Mindfulness Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_services_offered',
                'value' => 'Services Offered',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_client_concerns',
                'value' => 'Client Concerns',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_translator_settings',
                'value' => 'Translator Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_translator_services',
                'value' => 'Services Offered',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_translator_specializations',
                'value' => 'Specializations',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_yoga_therapist_settings',
                'value' => 'Yoga Therapist Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
            ],
            [
                'key' => 'admin_panel_sidebar_yoga_expertise',
                'value' => 'Expertise',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_countries',
                'value' => 'Countries',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_languages',
                'value' => 'Languages',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
            ],
            [
                'key' => 'admin_panel_sidebar_page_settings',
                'value' => 'Page Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
            ],
            [
                'key' => 'admin_panel_sidebar_homepage_settings',
                'value' => 'Homepage Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_gallery_settings',
                'value' => 'Gallery Page Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
            ],
            [
                'key' => 'admin_panel_sidebar_about_settings',
                'value' => 'About Us Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
            [
                'key' => 'admin_panel_sidebar_services_page_settings',
                'value' => 'Services Page Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'en',
            ],
            [
                'key' => 'admin_panel_sidebar_find_practitioner_settings',
                'value' => 'Find Practitioner Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'en',
            ],
            [
                'key' => 'admin_panel_sidebar_contact_us_settings',
                'value' => 'Contact Us Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
            ],
            [
                'key' => 'admin_panel_sidebar_admin_panel_settings',
                'value' => 'Admin Panel Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
            ],
            [
                'key' => 'admin_panel_sidebar_footer_settings',
                'value' => 'Footer Page Settings',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
            ],
            [
                'key' => 'admin_panel_sidebar_contact_messages',
                'value' => 'Contact Messages',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
            ],
            [
                'key' => 'admin_panel_sidebar_newsletters',
                'value' => 'Newsletters',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
            ],
        ];

        foreach ($settings as $setting) {
            HomepageSetting::updateOrCreate(
                ['key' => $setting['key'], 'language' => 'en'],
                $setting
            );
        }
    }
}
