<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HomepageSetting;

class AdminPanelSettingFrenchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General
            [
                'key' => 'profile_page_title',
                'value' => 'Paramètres du panneau d’administration',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'profile_page_subtitle',
                'value' => 'Gérez le contenu et les paramètres de votre panneau d’administration en un seul endroit.',
                'type' => 'textarea',
                'section' => 'admin_panel',
                'max_length' => 200,
                'language' => 'fr',
            ],
            [
                'key' => 'profile_page_banner_image',
                'value' => '',
                'type' => 'image',
                'section' => 'admin_panel',
                'max_length' => null,
                'language' => 'fr',
            ],
            // Statistics
            [
                'key' => 'profile_page_stat_1_label',
                'value' => 'Utilisateurs',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 20,
                'language' => 'fr',
            ],
            [
                'key' => 'profile_page_stat_1_value',
                'value' => '0',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 10,
                'language' => 'fr',
            ],
            [
                'key' => 'profile_page_stat_2_label',
                'value' => 'Services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 20,
                'language' => 'fr',
            ],
            [
                'key' => 'profile_page_stat_2_value',
                'value' => '0',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 10,
                'language' => 'fr',
            ],
            [
                'key' => 'profile_page_stat_3_label',
                'value' => 'Pays',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 20,
                'language' => 'fr',
            ],
            [
                'key' => 'profile_page_stat_3_value',
                'value' => '0',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 10,
                'language' => 'fr',
            ],
            // Sidebar
            [
                'key' => 'admin_panel_sidebar_pinned',
                'value' => 'Épinglé',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 30,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_general',
                'value' => 'Général',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 30,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_dashboard',
                'value' => 'Tableau de bord',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_my_profile',
                'value' => 'Mon profil',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_users',
                'value' => 'Utilisateurs',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_doctors',
                'value' => 'Médecins',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_practitioners',
                'value' => 'Praticiens',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_mindfulness_practitioners',
                'value' => 'Praticiens de pleine conscience',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_yoga_therapists',
                'value' => 'Thérapeutes de yoga',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_clients',
                'value' => 'Clients',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_translators',
                'value' => 'Traducteurs',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_backend_users',
                'value' => 'Utilisateurs du backend',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_admins',
                'value' => 'Administrateurs',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_finance_manager',
                'value' => 'Gestionnaire financier',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_content_manager',
                'value' => 'Gestionnaire de contenu',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_user_manager',
                'value' => 'Gestionnaire d’utilisateurs',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_credentials',
                'value' => 'Identifiants',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_testimonials',
                'value' => 'Témoignages',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_services',
                'value' => 'Services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_all_services',
                'value' => 'Tous les services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_service_packages',
                'value' => 'Forfaits de services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_service_categories',
                'value' => 'Catégories de services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_finance',
                'value' => 'Finance',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_packages',
                'value' => 'Forfaits',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_promo_codes',
                'value' => 'Codes promo',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_other_fees',
                'value' => 'Autres frais',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_reviews',
                'value' => 'Avis',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_practitioner_reviews',
                'value' => 'Praticien',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_master_settings',
                'value' => 'Paramètres maîtres',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_roles',
                'value' => 'Rôles',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_site_settings',
                'value' => 'Paramètres du site',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_doctor_settings',
                'value' => 'Paramètres du médecin',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_specializations',
                'value' => 'Spécialisations',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_ayurveda_expertises',
                'value' => 'Expertises ayurvédiques',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_health_conditions',
                'value' => 'Problèmes de santé',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_external_therapies',
                'value' => 'Thérapies externes',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_practitioner_settings',
                'value' => 'Paramètres du praticien',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_wellness_consultations',
                'value' => 'Consultations de bien-être',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 80,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_body_therapies',
                'value' => 'Massages et thérapies corporelles',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 80,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_other_modalities',
                'value' => 'Autres modalités',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_client_settings',
                'value' => 'Paramètres du client',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_consultation_preferences',
                'value' => 'Préférences de consultation',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 80,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_mindfulness_settings',
                'value' => 'Paramètres de pleine conscience',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_services_offered',
                'value' => 'Services offerts',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_client_concerns',
                'value' => 'Préoccupations des clients',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_translator_settings',
                'value' => 'Paramètres du traducteur',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_translator_services',
                'value' => 'Services offerts',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_translator_specializations',
                'value' => 'Spécialisations',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_yoga_therapist_settings',
                'value' => 'Paramètres du thérapeute de yoga',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_yoga_expertise',
                'value' => 'Expertise',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_countries',
                'value' => 'Pays',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_languages',
                'value' => 'Langues',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_page_settings',
                'value' => 'Paramètres de page',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_homepage_settings',
                'value' => 'Paramètres de la page d’accueil',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_gallery_settings',
                'value' => 'Paramètres de la page galerie',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_about_settings',
                'value' => 'Paramètres À propos de nous',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_services_page_settings',
                'value' => 'Paramètres de la page Services',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_find_practitioner_settings',
                'value' => 'Paramètres de recherche de praticiens',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_contact_us_settings',
                'value' => 'Paramètres Contactez-nous',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_admin_panel_settings',
                'value' => 'Paramètres du panneau d’administration',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_footer_settings',
                'value' => 'Paramètres du pied de page',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_contact_messages',
                'value' => 'Messages de contact',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 70,
                'language' => 'fr',
            ],
            [
                'key' => 'admin_panel_sidebar_newsletters',
                'value' => 'Newsletters',
                'type' => 'text',
                'section' => 'admin_panel',
                'max_length' => 60,
                'language' => 'fr',
            ],
        ];

        foreach ($settings as $setting) {
            HomepageSetting::updateOrCreate(
                ['key' => $setting['key'], 'language' => 'fr'],
                $setting
            );
        }
    }
}
