<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HomepageSetting;

class HomepageSettingFrenchSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // Hero Section
            [
                'key' => 'hero_title',
                'value' => 'Là où la sagesse indienne rencontre le bien-être moderne',
                'type' => 'text',
                'section' => 'hero',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'hero_subtitle',
                'value' => 'Un bien-être personnalisé guidé par des praticiens expérimentés et des experts holistiques de confiance.',
                'type' => 'text',
                'section' => 'hero',
                'max_length' => 100,
                'language' => 'fr',
            ],
            [
                'key' => 'hero_button_text',
                'value' => 'Découvrir notre histoire',
                'type' => 'text',
                'section' => 'hero',
                'max_length' => 25,
                'language' => 'fr',
            ],
            [
                'key' => 'hero_search_placeholder_1',
                'value' => 'Praticiens, traitements...',
                'type' => 'text',
                'section' => 'hero',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'hero_search_placeholder_2',
                'value' => 'Ville, code postal...',
                'type' => 'text',
                'section' => 'hero',
                'max_length' => 40,
                'language' => 'fr',
            ],

            // Services Section
            [
                'key' => 'services_title',
                'value' => 'Nos services',
                'type' => 'text',
                'section' => 'services',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'services_subtitle',
                'value' => 'Guérison holistique pour le corps, l’esprit et l’âme',
                'type' => 'text',
                'section' => 'services',
                'max_length' => 80,
                'language' => 'fr',
            ],
            [
                'key' => 'services_description',
                'value' => 'Découvrez nos traitements ayurvédiques spécialisés, nos thérapies de yoga transformatrices et nos conseils professionnels en pleine conscience. Connectez-vous à des experts du monde entier dédiés à votre parcours bien-être.',
                'type' => 'textarea',
                'section' => 'services',
                'max_length' => 250,
                'language' => 'fr',
            ],
            [
                'key' => 'services_button_text',
                'value' => 'Voir tous les services',
                'type' => 'text',
                'section' => 'services',
                'max_length' => 30,
                'language' => 'fr',
            ],

            // Practitioners Section
            [
                'key' => 'practitioners_title',
                'value' => 'Annuaire des praticiens',
                'type' => 'text',
                'section' => 'practitioners',
                'max_length' => 100,
                'language' => 'fr',
            ],
            [
                'key' => 'practitioners_description',
                'value' => 'Les praticiens Zaya sont expérimentés, compatissants et profondément engagés dans la guérison holistique. Ils vous guident avec des soins personnalisés et vous connectent à des experts spécialisés si nécessaire. Soutenus par les outils numériques de Zaya, les praticiens se concentrent pleinement sur la guérison tandis que la plateforme gère la coordination et la technologie. Ils travaillent au sein d’un réseau professionnel de confiance qui valorise l’éthique, la collaboration et la transparence. Ensemble, les praticiens Zaya créent des parcours de bien-être significatifs et à long terme.',
                'type' => 'textarea',
                'section' => 'practitioners',
                'max_length' => 1000,
                'language' => 'fr',
            ],
            [
                'key' => 'practitioners_browse_btn',
                'value' => 'Voir tous les praticiens',
                'type' => 'text',
                'section' => 'practitioners',
                'max_length' => 50,
                'language' => 'fr',
            ],

            // CTA Section
            [
                'key' => 'cta_title',
                'value' => 'Adoptons le bien-être ensemble',
                'type' => 'text',
                'section' => 'cta',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'cta_description',
                'value' => 'Connectez-vous avec des clients en quête de bien-être authentique. Listez vos services, gérez les réservations et rejoignez une communauté professionnelle d’experts ayurvédiques et du bien-être.',
                'type' => 'textarea',
                'section' => 'cta',
                'max_length' => 200,
                'language' => 'fr',
            ],
            [
                'key' => 'cta_button_text',
                'value' => 'Rejoindre notre équipe',
                'type' => 'text',
                'section' => 'cta',
                'max_length' => 25,
                'language' => 'fr',
            ],

            // Testimonials Section
            [
                'key' => 'testimonials_title',
                'value' => 'Véritables histoires de guérison',
                'type' => 'text',
                'section' => 'testimonials',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'testimonials_badge',
                'value' => 'Témoignages',
                'type' => 'text',
                'section' => 'testimonials',
                'max_length' => 20,
                'language' => 'fr',
            ],
            [
                'key' => 'testimonials_subtitle',
                'value' => 'Découvrez comment nos consultations ayurvédiques personnalisées ont aidé notre communauté à trouver équilibre, vitalité et bien-être durable.',
                'type' => 'textarea',
                'section' => 'testimonials',
                'max_length' => 200,
                'language' => 'fr',
            ],

            // Blog Section
            [
                'key' => 'blog_title',
                'value' => 'Journal de sagesse',
                'type' => 'text',
                'section' => 'blog',
                'max_length' => 30,
                'language' => 'fr',
            ],
            [
                'key' => 'blog_subtitle',
                'value' => 'Votre guide de la maîtrise ayurvédique',
                'type' => 'text',
                'section' => 'blog',
                'max_length' => 80,
                'language' => 'fr',
            ],
            [
                'key' => 'blog_button_text',
                'value' => 'Explorer le journal',
                'type' => 'text',
                'section' => 'blog',
                'max_length' => 25,
                'language' => 'fr',
            ],
            [
                'key' => 'blog_description',
                'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod te',
                'type' => 'textarea',
                'section' => 'blog',
                'max_length' => 150,
                'language' => 'fr',
            ],
            [
                'key' => 'blog_image_main',
                'value' => 'frontend/assets/Eucalyptus-Essential-Oil.png',
                'type' => 'image',
                'section' => 'blog',
                'language' => 'fr',
            ],
            [
                'key' => 'blog_post_1_image',
                'value' => 'frontend/assets/bed-air.png',
                'type' => 'image',
                'section' => 'blog',
                'language' => 'fr',
            ],
            [
                'key' => 'blog_post_1_title',
                'value' => 'L’art du sommeil réparateur',
                'type' => 'text',
                'section' => 'blog',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'blog_post_1_read_time',
                'value' => '7 min de lecture',
                'type' => 'text',
                'section' => 'blog',
                'max_length' => 15,
                'language' => 'fr',
            ],
            [
                'key' => 'blog_post_2_image',
                'value' => 'frontend/assets/ayurvedha-medicine.png',
                'type' => 'image',
                'section' => 'blog',
                'language' => 'fr',
            ],
            [
                'key' => 'blog_post_2_title',
                'value' => 'Rituels du matin pour l’énergie',
                'type' => 'text',
                'section' => 'blog',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'blog_post_2_read_time',
                'value' => '15 min de lecture',
                'type' => 'text',
                'section' => 'blog',
                'max_length' => 15,
                'language' => 'fr',
            ],
            [
                'key' => 'blog_footer_text',
                'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod te',
                'type' => 'textarea',
                'section' => 'blog',
                'max_length' => 150,
                'language' => 'fr',
            ],

            // About Us Section
            [
                'key' => 'about_title',
                'value' => 'À propos',
                'type' => 'text',
                'section' => 'about_page',
                'max_length' => 30,
                'language' => 'fr',
            ],
            [
                'key' => 'about_banner_image',
                'value' => 'frontend/assets/about-us-bg.png',
                'type' => 'image',
                'section' => 'about_page',
                'language' => 'fr',
            ],
            [
                'key' => 'about_banner_title',
                'value' => "Les cœurs et les esprits\nDerrière ZAYA",
                'type' => 'textarea',
                'section' => 'about_page',
                'max_length' => 80,
                'language' => 'fr',
            ],
            [
                'key' => 'about_banner_button_text',
                'value' => 'Rencontrer notre équipe',
                'type' => 'text',
                'section' => 'about_page',
                'max_length' => 25,
                'language' => 'fr',
            ],
            [
                'key' => 'about_description',
                'value' => 'ZAYA est plus qu’une plateforme : c’est un pont entre la sagesse ayurvédique traditionnelle et le bien-être moderne. Découvrez l’équipe dédiée qui aide les praticiens et offre aux clients un parcours fluide vers la santé holistique.',
                'type' => 'textarea',
                'section' => 'about_page',
                'max_length' => 300,
                'language' => 'fr',
            ],
            [
                'key' => 'about_team_title',
                'value' => 'Rencontrez l’équipe',
                'type' => 'text',
                'section' => 'about_page',
                'max_length' => 40,
                'language' => 'fr',
            ],
            [
                'key' => 'about_team_subtitle',
                'value' => 'Les visionnaires derrière ZAYA Wellness',
                'type' => 'text',
                'section' => 'about_page',
                'max_length' => 80,
                'language' => 'fr',
            ],
            [
                'key' => 'about_what_we_do_title',
                'value' => 'Que faisons-nous ?',
                'type' => 'text',
                'section' => 'about_page',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'about_vision_title',
                'value' => 'Notre vision',
                'type' => 'text',
                'section' => 'about_page',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'about_vision_description',
                'value' => "Notre vision est de créer un écosystème de bien-être mondial, dirigé par des praticiens, enraciné dans l'Ayurveda et les soins holistiques. Zaya vise à rendre le bien-être authentique, éthique et personnalisé accessible au-delà des frontières grâce à une collaboration de confiance et à l'utilisation réfléchie de la technologie. Nous envisageons un avenir où les praticiens sont responsabilisés, où les spécialistes travaillent ensemble de manière transparente et où vous bénéficiez de soins qui soutiennent véritablement le bien-être à long terme.",
                'type' => 'textarea',
                'section' => 'about_page',
                'max_length' => 1000,
                'language' => 'fr',
            ],
            [
                'key' => 'about_mission_title',
                'value' => 'Notre mission',
                'type' => 'text',
                'section' => 'about_page',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'about_mission_description',
                'value' => "Nous avons pour mission de soutenir les praticiens et de simplifier le processus de bien-être pour tous à travers le monde. Animée par une passion pour la santé holistique, notre équipe donne aux praticiens les moyens de fournir les meilleurs soins que vous méritez.",
                'type' => 'textarea',
                'section' => 'about_page',
                'max_length' => 1000,
                'language' => 'fr',
            ],

            // Services Page Section
            [
                'key' => 'services_page_badge',
                'value' => 'Nos services',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 30,
                'language' => 'fr',
            ],
            [
                'key' => 'services_page_title',
                'value' => "Adoptez le bien-être\nholistique",
                'type' => 'textarea',
                'section' => 'services_page',
                'max_length' => 60,
                'language' => 'fr',
            ],
            [
                'key' => 'services_page_subtitle',
                'value' => 'Un accompagnement détaillé vers la vitalité physique, la clarté mentale et l’harmonie spirituelle.',
                'type' => 'textarea',
                'section' => 'services_page',
                'max_length' => 150,
                'language' => 'fr',
            ],
            [
                'key' => 'services_page_description',
                'value' => 'ZAYA Wellness sert de pont mondial pour ceux qui recherchent des soins authentiques et experts, enracinés dans la sagesse indienne traditionnelle. Chaque service proposé sur notre plateforme est fourni par un praticien dont le parcours en Ayurveda, Yoga ou santé holistique a été rigoureusement évalué par notre commission d’approbation.',
                'type' => 'textarea',
                'section' => 'services_page',
                'max_length' => 400,
                'language' => 'fr',
            ],
            [
                'key' => 'services_page_image',
                'value' => 'frontend/assets/services-page-bg.png',
                'type' => 'image',
                'section' => 'services_page',
                'language' => 'fr',
            ],
            // Stats
            [
                'key' => 'services_stat_1_count',
                'value' => '300',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 10,
                'language' => 'fr',
            ],
            [
                'key' => 'services_stat_1_label',
                'value' => 'Sessions terminées',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 30,
                'language' => 'fr',
            ],
            [
                'key' => 'services_stat_2_count',
                'value' => '50+',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 10,
                'language' => 'fr',
            ],
            [
                'key' => 'services_stat_2_label',
                'value' => 'Praticiens certifiés',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 30,
                'language' => 'fr',
            ],
            [
                'key' => 'services_stat_3_count',
                'value' => '99%',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 10,
                'language' => 'fr',
            ],
            [
                'key' => 'services_stat_3_label',
                'value' => 'Avis positifs',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 30,
                'language' => 'fr',
            ],
            [
                'key' => 'services_stat_4_count',
                'value' => '10',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 10,
                'language' => 'fr',
            ],
            [
                'key' => 'services_stat_4_label',
                'value' => 'Années de tradition',
                'type' => 'text',
                'section' => 'services_page',
                'max_length' => 30,
                'language' => 'fr',
            ],

            // Social Links
            [
                'section' => 'social_links',
                'key' => 'facebook_url',
                'value' => 'https://facebook.com',
                'type' => 'text',
                'language' => 'fr',
            ],
            [
                'section' => 'social_links',
                'key' => 'instagram_url',
                'value' => 'https://instagram.com',
                'type' => 'text',
                'language' => 'fr',
            ],
            [
                'section' => 'social_links',
                'key' => 'whatsapp_number',
                'value' => '+911234567890',
                'type' => 'text',
                'language' => 'fr',
            ],
            [
                'section' => 'social_links',
                'key' => 'website_url',
                'value' => 'https://zaya.com',
                'type' => 'text',
                'language' => 'fr',
            ],
            // Contact Us Page
            [
                'key' => 'contact_banner_title',
                'value' => 'Contactez-nous',
                'type' => 'text',
                'section' => 'contact_page',
                'max_length' => 50,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_banner_subtitle',
                'value' => 'Zaya vous connecte avec des praticiens ayurvédiques de confiance pour des conseils bien-être personnalisés, des traitements et un soutien continu pour praticiens ou clients.',
                'type' => 'textarea',
                'section' => 'contact_page',
                'max_length' => 500,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_info_location',
                'value' => 'No. 1234, 5ème Avenue,<br>Kochi, Inde',
                'type' => 'textarea',
                'section' => 'contact_page',
                'max_length' => 200,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_info_phone',
                'value' => '+91 123 456 7890<br>+91 987 654 3210',
                'type' => 'textarea',
                'section' => 'contact_page',
                'max_length' => 100,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_info_email',
                'value' => 'support@zayawellness.com<br>info@zayawellness.com',
                'type' => 'textarea',
                'section' => 'contact_page',
                'max_length' => 100,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_info_working_hours',
                'value' => 'Lun - Ven: 9h - 18h<br>Sam: 10h - 14h',
                'type' => 'textarea',
                'section' => 'contact_page',
                'max_length' => 100,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_form_title',
                'value' => 'Envoyez-nous un message',
                'type' => 'text',
                'section' => 'contact_page',
                'max_length' => 100,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_form_subtitle',
                'value' => 'Votre chemin vers le bien-être commence par une conversation',
                'type' => 'text',
                'section' => 'contact_page',
                'max_length' => 200,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_support_practitioner_title',
                'value' => 'Demandes des praticiens',
                'type' => 'text',
                'section' => 'contact_page',
                'max_length' => 100,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_support_practitioner_text',
                'value' => 'Connectez-vous avec des Vaidyas ayurvédiques expérimentés via Zaya. Rejoignez-nous.',
                'type' => 'textarea',
                'section' => 'contact_page',
                'max_length' => 300,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_support_client_title',
                'value' => 'Support client',
                'type' => 'text',
                'section' => 'contact_page',
                'max_length' => 100,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_support_client_text',
                'value' => 'Besoin d’aide ? Consultez notre FAQ ou contactez-nous via le formulaire ci-dessus.',
                'type' => 'textarea',
                'section' => 'contact_page',
                'max_length' => 300,
                'language' => 'fr',
            ],
            [
                'key' => 'contact_faq_title',
                'value' => 'Foire Aux Questions',
                'type' => 'text',
                'section' => 'contact_page',
                'max_length' => 100,
                'language' => 'fr',
            ],
        ];

        foreach ($settings as $setting) {
            HomepageSetting::updateOrCreate(
                ['key' => $setting['key'], 'language' => 'fr'],
                $setting
            );
        }
    }
}
